services:
  backend:
    build: ./backend
    container_name: fedapp_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/models:/app/models
      - ./backend/datasets:/app/datasets
    env_file:
      - .env  # Reads the root env file
    depends_on:
      - db
    networks:
      - fed_net

  fl-server:
    build: ./fl-server
    container_name: fedapp_fl_server
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PROJECT_ID=1
      - API_BASE=${INTERNAL_API_URL} # Connects securely within Docker
    depends_on:
      - backend
    networks:
      - fed_net

  frontend:
    build:
      context: ./frontend
      args:
        # Passes the Cloudflare domains to Vite during the build
        - VITE_API_BASE_URL=${DOMAIN_API}
        - VITE_WS_URL=${WS_URL}
    container_name: fedapp_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fed_net

  db:
    image: mysql:8.0
    container_name: fedapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - fed_net

volumes:
  db_data:

networks:
  fed_net:
    driver: bridge